$(document).ready(function(){
	$("#d").hide();
	$("#p").hide();
	$("#m").hide();

  $("#d-click").click(function(){
    $("#d").toggle();
  });
});
$(document).ready(function(){
  $("#p-click").click(function(){
    $("#p").toggle();
  });
});
$(document).ready(function(){
  $("#m-click").click(function(){
    $("#m").toggle();
  });
});
